(
    name: "FyroxGfxGlass",

    resources: [
        (
            // The frame as it was before glass was drawn. Bound by `GlassMaterial`.
            name: "sceneColor",
            kind: Texture(kind: Sampler2D, fallback: Black),
            binding: 0
        ),
        (
            name: "fyrox_sceneDepth",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 1
        ),
        (
            name: "normalTexture",
            kind: Texture(kind: Sampler2D, fallback: Normal),
            binding: 2
        ),
        (
            name: "properties",
            kind: PropertyGroup([
                (
                    name: "tint",
                    kind: Color(r: 255, g: 255, b: 255, a: 255),
                ),
                (
                    name: "tintStrength",
                    kind: Float(value: 0.35),
                ),
                (
                    name: "indexOfRefraction",
                    kind: Float(value: 1.5),
                ),
                (
                    name: "distortion",
                    kind: Float(value: 0.3),
                ),
                (
                    name: "waviness",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "waveScale",
                    kind: Float(value: 4.0),
                ),
                (
                    name: "blur",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "specularStrength",
                    kind: Float(value: 1.0),
                ),
                (
                    name: "shininess",
                    kind: Float(value: 96.0),
                ),
                (
                    name: "reflectivity",
                    kind: Float(value: 0.6),
                ),
                (
                    name: "emission",
                    kind: Color(r: 0, g: 0, b: 0, a: 255),
                ),
                (
                    name: "emissionStrength",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "texCoordScale",
                    kind: Vector2(value: (1.0, 1.0)),
                ),
            ]),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
        (
            name: "fyrox_cameraData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 2
        ),
        (
            name: "fyrox_lightsBlock",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 3
        ),
        (
            name: "fyrox_lightData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 4
        ),
    ],

    // Glass is drawn only by the refraction pass, after everything behind it is on screen. It
    // neither fills the G-buffer nor casts shadows, so light passes through it.
    disabled_passes: ["GBuffer", "Forward", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Refraction",
            draw_parameters: DrawParameters(
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: false,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                layout(location = 0) in vec3 vertexPosition;
                layout(location = 1) in vec2 vertexTexCoord;
                layout(location = 2) in vec3 vertexNormal;
                layout(location = 3) in vec4 vertexTangent;

                out vec3 worldPosition;
                out vec2 texCoord;
                out vec3 normal;
                out vec3 tangent;
                out vec3 binormal;

                void main()
                {
                    mat4 world = fyrox_instanceData.worldMatrix;
                    worldPosition = (world * vec4(vertexPosition, 1.0)).xyz;
                    texCoord = vertexTexCoord;
                    normal = normalize((world * vec4(vertexNormal, 0.0)).xyz);
                    tangent = normalize((world * vec4(vertexTangent.xyz, 0.0)).xyz);
                    binormal = cross(normal, tangent) * vertexTangent.w;
                    gl_Position = fyrox_instanceData.worldViewProjection * vec4(vertexPosition, 1.0);
                }
               "#,

           fragment_shader:
               r#"
                out vec4 FragColor;

                in vec3 worldPosition;
                in vec2 texCoord;
                in vec3 normal;
                in vec3 tangent;
                in vec3 binormal;

                vec2 projectToScreen(vec3 point) {
                    vec4 clip = fyrox_cameraData.viewProjectionMatrix * vec4(point, 1.0);
                    // Render targets are stored bottom row first here, as screen v runs.
                    return clip.xy / clip.w * 0.5;
                }

                vec3 sampleScene(vec2 uv, vec2 texel) {
                    vec2 radius = properties.blur * texel;
                    vec3 color = texture(sceneColor, uv).rgb * 0.4;
                    color += texture(sceneColor, uv + vec2(radius.x, 0.0)).rgb * 0.15;
                    color += texture(sceneColor, uv - vec2(radius.x, 0.0)).rgb * 0.15;
                    color += texture(sceneColor, uv + vec2(0.0, radius.y)).rgb * 0.15;
                    color += texture(sceneColor, uv - vec2(0.0, radius.y)).rgb * 0.15;
                    return color;
                }

                void main()
                {
                    mat3 tbn = mat3(normalize(tangent), normalize(binormal), normalize(normal));
                    vec3 mapped = texture(normalTexture, texCoord * properties.texCoordScale).xyz * 2.0 - 1.0;
                    vec3 n = normalize(tbn * mapped);
                    // Ripples for glass that is not perfectly flat.
                    vec3 p = worldPosition * properties.waveScale;
                    n = normalize(n + properties.waviness * vec3(
                        sin(p.y * 1.7 + p.z * 2.3),
                        sin(p.x * 2.1 + p.z * 1.3),
                        sin(p.x * 1.1 + p.y * 2.9)
                    ));
                    if (!gl_FrontFacing) {
                        n = -n;
                    }

                    vec3 toCamera = normalize(fyrox_cameraData.position - worldPosition);
                    vec3 incident = -toCamera;

                    // How far the refracted ray bends away from the straight one, seen on screen.
                    float ior = max(properties.indexOfRefraction, 1.0);
                    vec3 refracted = refract(incident, n, 1.0 / ior);
                    vec2 screenShift = projectToScreen(worldPosition + refracted * properties.distortion)
                        - projectToScreen(worldPosition + incident * properties.distortion);

                    vec2 size = vec2(textureSize(sceneColor, 0));
                    vec2 texel = 1.0 / size;
                    vec2 straightUv = gl_FragCoord.xy * texel;
                    vec2 bentUv = clamp(straightUv + screenShift, vec2(0.0), vec2(1.0));

                    // Anything between the camera and the glass must not show up in the glass.
                    float depthAtBent = texture(fyrox_sceneDepth, bentUv).r;
                    vec2 uv = depthAtBent < gl_FragCoord.z ? straightUv : bentUv;

                    vec3 tint = S_SRGBToLinear(properties.tint).rgb;
                    vec3 transmitted = sampleScene(uv, texel) * mix(vec3(1.0), tint, properties.tintStrength);

                    // Schlick's approximation of how much is reflected instead of let through.
                    float f0 = pow((ior - 1.0) / (ior + 1.0), 2.0);
                    float cosTheta = clamp(dot(n, toCamera), 0.0, 1.0);
                    float fresnel = clamp((f0 + (1.0 - f0) * pow(1.0 - cosTheta, 5.0)) * properties.reflectivity, 0.0, 1.0);
                    vec3 reflected = fyrox_lightData.ambientLightColor.rgb * mix(vec3(1.0), tint, 0.5);

                    vec3 highlights = vec3(0.0);
                    for (int i = 0; i < min(fyrox_lightsBlock.lightCount, 16); ++i) {
                        float halfHotspotAngleCos = fyrox_lightsBlock.lightsParameters[i].x;
                        float halfConeAngleCos = fyrox_lightsBlock.lightsParameters[i].y;
                        vec3 lightColor = fyrox_lightsBlock.lightsColorRadius[i].xyz;
                        float radius = fyrox_lightsBlock.lightsColorRadius[i].w;
                        vec3 toFragment = worldPosition - fyrox_lightsBlock.lightsPosition[i];
                        float dist = length(toFragment);
                        vec3 toLight = -toFragment / max(dist, 0.0001);
                        // Point and directional lights come with both cone angles equal, which
                        // would make the smoothstep below divide by zero: they shine everywhere.
                        float cone = 1.0;
                        if (halfHotspotAngleCos - halfConeAngleCos > 0.0001) {
                            cone = smoothstep(halfConeAngleCos, halfHotspotAngleCos, dot(-toLight, fyrox_lightsBlock.lightsDirection[i]));
                        }
                        float attenuation = S_LightDistanceAttenuation(dist, radius) * cone;
                        vec3 halfway = normalize(toLight + toCamera);
                        highlights += lightColor * attenuation * pow(max(dot(n, halfway), 0.0), properties.shininess);
                    }

                    // Light the glass itself gives off, as a lamp behind a pane does.
                    vec3 emitted = S_SRGBToLinear(properties.emission).rgb * properties.emissionStrength;

                    vec3 color = mix(transmitted, reflected, fresnel)
                        + highlights * properties.specularStrength
                        + emitted;
                    FragColor = vec4(color, 1.0);
                }
               "#,
        ),
    ],
)
