(
    name: "FyroxGfxGlass",

    resources: [
        (
            // The frame as it was before glass was drawn. Bound by `GlassMaterial`.
            name: "sceneColor",
            kind: Texture(kind: Sampler2D, fallback: Black),
            binding: 0
        ),
        (
            name: "fyrox_sceneDepth",
            kind: Texture(kind: DepthSampler2D, fallback: White),
            binding: 1
        ),
        (
            name: "normalTexture",
            kind: Texture(kind: Sampler2D, fallback: Normal),
            binding: 2
        ),
        (
            name: "properties",
            kind: PropertyGroup([
                (
                    name: "tint",
                    kind: Color(r: 255, g: 255, b: 255, a: 255),
                ),
                (
                    name: "tintStrength",
                    kind: Float(value: 0.35),
                ),
                (
                    name: "indexOfRefraction",
                    kind: Float(value: 1.5),
                ),
                (
                    name: "distortion",
                    kind: Float(value: 0.3),
                ),
                (
                    name: "waviness",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "waveScale",
                    kind: Float(value: 4.0),
                ),
                (
                    name: "blur",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "specularStrength",
                    kind: Float(value: 1.0),
                ),
                (
                    name: "shininess",
                    kind: Float(value: 96.0),
                ),
                (
                    name: "reflectivity",
                    kind: Float(value: 0.6),
                ),
                (
                    name: "emission",
                    kind: Color(r: 0, g: 0, b: 0, a: 255),
                ),
                (
                    name: "emissionStrength",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "texCoordScale",
                    kind: Vector2(value: (1.0, 1.0)),
                ),
            ]),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
        (
            name: "fyrox_cameraData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 2
        ),
        (
            name: "fyrox_lightsBlock",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 3
        ),
        (
            name: "fyrox_lightData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 4
        ),
    ],

    // Glass is drawn only by the refraction pass, after everything behind it is on screen. It
    // neither fills the G-buffer nor casts shadows, so light passes through it.
    disabled_passes: ["GBuffer", "Forward", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Refraction",
            draw_parameters: DrawParameters(
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: false,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                struct VertexInput {
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) worldPosition: vec3f,
                    @location(1) texCoord: vec2f,
                    @location(2) normal: vec3f,
                    @location(3) tangent: vec3f,
                    @location(4) binormal: vec3f,
                };

                @vertex fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;
                    let world = fyrox_instanceData.worldMatrix;
                    output.worldPosition = (world * vec4f(input.vertexPosition, 1.0)).xyz;
                    output.texCoord = input.vertexTexCoord;
                    output.normal = normalize((world * vec4f(input.vertexNormal, 0.0)).xyz);
                    output.tangent = normalize((world * vec4f(input.vertexTangent.xyz, 0.0)).xyz);
                    output.binormal = cross(output.normal, output.tangent) * input.vertexTangent.w;
                    output.position = fyrox_instanceData.worldViewProjection * vec4f(input.vertexPosition, 1.0);
                    return output;
                }
               "#,

           fragment_shader:
               r#"
                fn projectToScreen(point: vec3f) -> vec2f {
                    let clip = fyrox_cameraData.viewProjectionMatrix * vec4f(point, 1.0);
                    // Render targets are stored top row first here, so screen v runs against
                    // clip-space y.
                    return vec2f(clip.x, -clip.y) / clip.w * 0.5;
                }

                fn sampleScene(uv: vec2f, texel: vec2f) -> vec3f {
                    let radius = properties.blur * texel;
                    var color = textureSample(sceneColor_tex, sceneColor_samp, uv).rgb * 0.4;
                    color += textureSample(sceneColor_tex, sceneColor_samp, uv + vec2f(radius.x, 0.0)).rgb * 0.15;
                    color += textureSample(sceneColor_tex, sceneColor_samp, uv - vec2f(radius.x, 0.0)).rgb * 0.15;
                    color += textureSample(sceneColor_tex, sceneColor_samp, uv + vec2f(0.0, radius.y)).rgb * 0.15;
                    color += textureSample(sceneColor_tex, sceneColor_samp, uv - vec2f(0.0, radius.y)).rgb * 0.15;
                    return color;
                }

                @fragment fn fs_main(
                    @builtin(position) fragCoord: vec4f,
                    @builtin(front_facing) frontFacing: bool,
                    @location(0) worldPosition: vec3f,
                    @location(1) texCoord: vec2f,
                    @location(2) normalIn: vec3f,
                    @location(3) tangent: vec3f,
                    @location(4) binormal: vec3f,
                ) -> @location(0) vec4f {
                    let tbn = mat3x3f(normalize(tangent), normalize(binormal), normalize(normalIn));
                    let mapped = textureSample(normalTexture_tex, normalTexture_samp, texCoord * properties.texCoordScale).xyz * 2.0 - 1.0;
                    var n = normalize(tbn * mapped);
                    // Ripples for glass that is not perfectly flat.
                    let p = worldPosition * properties.waveScale;
                    n = normalize(n + properties.waviness * vec3f(
                        sin(p.y * 1.7 + p.z * 2.3),
                        sin(p.x * 2.1 + p.z * 1.3),
                        sin(p.x * 1.1 + p.y * 2.9)
                    ));
                    if (!frontFacing) {
                        n = -n;
                    }

                    let toCamera = normalize(fyrox_cameraData.position - worldPosition);
                    let incident = -toCamera;

                    // How far the refracted ray bends away from the straight one, seen on screen.
                    let ior = max(properties.indexOfRefraction, 1.0);
                    let refracted = refract(incident, n, 1.0 / ior);
                    let screenShift = projectToScreen(worldPosition + refracted * properties.distortion)
                        - projectToScreen(worldPosition + incident * properties.distortion);

                    let size = vec2f(textureDimensions(sceneColor_tex, 0));
                    let texel = 1.0 / size;
                    let straightUv = fragCoord.xy * texel;
                    let bentUv = clamp(straightUv + screenShift, vec2f(0.0), vec2f(1.0));

                    // Anything between the camera and the glass must not show up in the glass.
                    let depthAtBent = textureSample(fyrox_sceneDepth_tex, fyrox_sceneDepth_samp, bentUv);
                    let uv = select(bentUv, straightUv, depthAtBent < fragCoord.z);

                    let tint = S_SRGBToLinear(properties.tint).rgb;
                    let transmitted = sampleScene(uv, texel) * mix(vec3f(1.0), tint, properties.tintStrength);

                    // Schlick's approximation of how much is reflected instead of let through.
                    let f0 = pow((ior - 1.0) / (ior + 1.0), 2.0);
                    let cosTheta = clamp(dot(n, toCamera), 0.0, 1.0);
                    let fresnel = clamp((f0 + (1.0 - f0) * pow(1.0 - cosTheta, 5.0)) * properties.reflectivity, 0.0, 1.0);
                    let reflected = fyrox_lightData.ambientLightColor.rgb * mix(vec3f(1.0), tint, 0.5);

                    var highlights = vec3f(0.0);
                    for (var i: i32 = 0; i < min(i32(fyrox_lightsBlock.lightCount), 16); i++) {
                        let halfHotspotAngleCos = fyrox_lightsBlock.lightsParameters[i].x;
                        let halfConeAngleCos = fyrox_lightsBlock.lightsParameters[i].y;
                        let lightColor = fyrox_lightsBlock.lightsColorRadius[i].xyz;
                        let radius = fyrox_lightsBlock.lightsColorRadius[i].w;
                        let toFragment = worldPosition - fyrox_lightsBlock.lightsPosition[i];
                        let dist = length(toFragment);
                        let toLight = -toFragment / max(dist, 0.0001);
                        // Point and directional lights come with both cone angles equal, which
                        // would make the smoothstep below divide by zero: they shine everywhere.
                        var cone = 1.0;
                        if (halfHotspotAngleCos - halfConeAngleCos > 0.0001) {
                            cone = smoothstep(halfConeAngleCos, halfHotspotAngleCos, dot(-toLight, fyrox_lightsBlock.lightsDirection[i]));
                        }
                        let attenuation = S_LightDistanceAttenuation(dist, radius) * cone;
                        let halfway = normalize(toLight + toCamera);
                        highlights += lightColor * attenuation * pow(max(dot(n, halfway), 0.0), properties.shininess);
                    }

                    // Light the glass itself gives off, as a lamp behind a pane does.
                    let emitted = S_SRGBToLinear(properties.emission).rgb * properties.emissionStrength;

                    let color = mix(transmitted, reflected, fresnel)
                        + highlights * properties.specularStrength
                        + emitted;
                    return vec4f(color, 1.0);
                }
               "#,
        ),
    ],
)
